name: Test Nexus Server

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: Test Nexus Server
    env:
      # For Test Server
      NEXUS_INSTANCE: "true"

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Test Nexus Server
        uses: addnab/docker-run-action@v3
        with:
          image: sonatype/nexus3
          options: -v /nexus-data
          run: |
            chmod +x ./gradlew
            ./gradlew test