name: Test Jenkins Server

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: Test Jenkins Server
    env:
      # For Test Server
      JENKINS_USERNAME: "admin"
      JENKINS_PASSWORD: "password"

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Test Jenkins Server
        uses: addnab/docker-run-action@v3
        with:
          image: jenkins/jenkins:lts
          options: -v /jenkins-data
          run: |
            chmod +x ./gradlew
            ./gradlew test